/**
 * Paper-grain overlay: one tiny seamless PNG tile (public/world/grain.png, generated by
 * scripts/generate-grain.mjs) repeated with CSS and blended over a whole scene. A single composited
 * layer instead of per-object SVG filters keeps dragging smooth on modest tablets.
 *
 * Place it as the last child of a `position: relative` scene container. It never takes pointer events.
 */
export interface GrainProps {
  /** 0..1, default from the theme token --world-grain-opacity. */
  opacity?: number
  className?: string
}

export function Grain({ opacity, className }: GrainProps) {
  return (
    <div
      aria-hidden="true"
      data-testid="world-grain"
      className={['world-grain', className].filter(Boolean).join(' ')}
      style={opacity === undefined ? undefined : { opacity }}
    />
  )
}
