import type { Sticker } from './catalog'

/** Original sticker collection (emoji-composed, no third-party artwork). Ids never change: they are stored in the progress. */
export const STICKER_DATA: readonly Sticker[] = [
  { id: 'maduixa', emoji: '🍓', name: 'Maduixa', series: 'bosc', rarity: 'comuna', source: 'joc' },
  { id: 'arc', emoji: '🌈', name: 'Arc de Sant Martí', series: 'bosc', rarity: 'rara', source: 'joc' },
  { id: 'unicorn', emoji: '🦄', name: 'Unicorn', series: 'bosc', rarity: 'rara', source: 'joc' },
  { id: 'flor', emoji: '🌸', name: 'Flor de cirerer', series: 'bosc', rarity: 'comuna', source: 'joc' },
  { id: 'papallona', emoji: '🦋', name: 'Papallona', series: 'bosc', rarity: 'comuna', source: 'joc' },
  { id: 'gira-sol', emoji: '🌻', name: 'Gira-sol', series: 'bosc', rarity: 'comuna', source: 'joc' },
  { id: 'trevol', emoji: '🍀', name: 'Trèvol de la sort', series: 'bosc', rarity: 'comuna', source: 'joc' },
  { id: 'guineu', emoji: '🦊', name: 'Guineu', series: 'bosc', rarity: 'comuna', source: 'joc' },
  { id: 'panda', emoji: '🐼', name: 'Panda', series: 'bosc', rarity: 'comuna', source: 'joc' },
  { id: 'conill', emoji: '🐰', name: 'Conillet', series: 'bosc', rarity: 'comuna', source: 'joc' },
  { id: 'lluna', emoji: '🌙', name: 'Lluna', series: 'bosc', rarity: 'comuna', source: 'joc' },
  { id: 'estel', emoji: '⭐', name: 'Estel', series: 'bosc', rarity: 'comuna', source: 'joc' },
  { id: 'dofi', emoji: '🐬', name: 'Dofí', series: 'platja', rarity: 'rara', source: 'joc' },
  { id: 'tortuga', emoji: '🐢', name: 'Tortuga', series: 'platja', rarity: 'comuna', source: 'joc' },
  { id: 'gelat', emoji: '🍦', name: 'Gelat', series: 'platja', rarity: 'comuna', source: 'joc' },
  { id: 'sindria', emoji: '🍉', name: 'Síndria', series: 'platja', rarity: 'comuna', source: 'joc' },
  { id: 'petxina', emoji: '🐚', name: 'Petxina', series: 'platja', rarity: 'comuna', source: 'joc' },
  { id: 'pop', emoji: '🐙', name: 'Pop', series: 'platja', rarity: 'rara', source: 'joc' },
  { id: 'pingui', emoji: '🐧', name: 'Pingüí', series: 'platja', rarity: 'comuna', source: 'joc' },
  { id: 'globus', emoji: '🎈', name: 'Globus', series: 'platja', rarity: 'comuna', source: 'joc' },
  { id: 'piruleta', emoji: '🍭', name: 'Piruleta', series: 'platja', rarity: 'comuna', source: 'joc' },
  { id: 'sol', emoji: '☀️', name: 'Sol', series: 'platja', rarity: 'comuna', source: 'joc' },
  { id: 'cranc', emoji: '🦀', name: 'Cranc', series: 'platja', rarity: 'comuna', source: 'joc' },
  { id: 'balena', emoji: '🐳', name: 'Balena', series: 'platja', rarity: 'rara', source: 'joc' },
  { id: 'corona', emoji: '👑', name: 'Corona', series: 'castell', rarity: 'rara', source: 'joc' },
  { id: 'diamant', emoji: '💎', name: 'Diamant', series: 'castell', rarity: 'rara', source: 'joc' },
  { id: 'magdalena', emoji: '🧁', name: 'Magdalena', series: 'castell', rarity: 'comuna', source: 'joc' },
  { id: 'donut', emoji: '🍩', name: 'Dònut', series: 'castell', rarity: 'comuna', source: 'joc' },
  { id: 'pastis', emoji: '🎂', name: 'Pastís', series: 'castell', rarity: 'comuna', source: 'joc' },
  { id: 'llac', emoji: '🎀', name: 'Llaç', series: 'castell', rarity: 'comuna', source: 'joc' },
  { id: 'cor-negre', emoji: '🖤', name: 'Cor punk', series: 'castell', rarity: 'epica', source: 'joc' },
  { id: 'calavera', emoji: '💀', name: 'Calavereta', series: 'castell', rarity: 'epica', source: 'joc' },
  { id: 'castell', emoji: '🏰', name: 'Castell', series: 'castell', rarity: 'rara', source: 'joc' },
  { id: 'coet', emoji: '🚀', name: 'Coet', series: 'castell', rarity: 'rara', source: 'joc' },
  { id: 'planeta', emoji: '🪐', name: 'Planeta', series: 'castell', rarity: 'rara', source: 'joc' },
  { id: 'musica', emoji: '🎵', name: 'Música', series: 'castell', rarity: 'comuna', source: 'joc' },
  { id: 'gat', emoji: '🐱', name: 'Gat', series: 'animals', rarity: 'comuna', source: 'joc' },
  { id: 'gos', emoji: '🐶', name: 'Gos', series: 'animals', rarity: 'comuna', source: 'joc' },
  { id: 'lleo', emoji: '🦁', name: 'Lleó', series: 'animals', rarity: 'comuna', source: 'joc' },
  { id: 'elefant', emoji: '🐘', name: 'Elefant', series: 'animals', rarity: 'comuna', source: 'joc' },
  { id: 'girafa', emoji: '🦒', name: 'Girafa', series: 'animals', rarity: 'comuna', source: 'joc' },
  { id: 'mico', emoji: '🐵', name: 'Mico', series: 'animals', rarity: 'comuna', source: 'joc' },
  { id: 'porquet', emoji: '🐷', name: 'Porquet', series: 'animals', rarity: 'comuna', source: 'joc' },
  { id: 'granota', emoji: '🐸', name: 'Granota', series: 'animals', rarity: 'rara', source: 'joc' },
  { id: 'abella', emoji: '🐝', name: 'Abella', series: 'animals', rarity: 'rara', source: 'joc' },
  { id: 'mussol', emoji: '🦉', name: 'Mussol', series: 'animals', rarity: 'rara', source: 'joc' },
  { id: 'erico', emoji: '🦔', name: 'Eriçó', series: 'animals', rarity: 'epica', source: 'joc' },
  { id: 'cavall', emoji: '🐴', name: 'Cavall', series: 'animals', rarity: 'epica', source: 'joc' },
  { id: 'lluna-plena', emoji: '🌕', name: 'Lluna plena', series: 'espai', rarity: 'comuna', source: 'joc' },
  { id: 'ovni', emoji: '🛸', name: 'Ovni', series: 'espai', rarity: 'comuna', source: 'joc' },
  { id: 'satellit', emoji: '🛰️', name: 'Satèl·lit', series: 'espai', rarity: 'comuna', source: 'joc' },
  { id: 'cometa', emoji: '☄️', name: 'Cometa', series: 'espai', rarity: 'comuna', source: 'joc' },
  { id: 'terra', emoji: '🌍', name: 'La Terra', series: 'espai', rarity: 'comuna', source: 'joc' },
  { id: 'astronauta', emoji: '👩‍🚀', name: 'Astronauta', series: 'espai', rarity: 'comuna', source: 'joc' },
  { id: 'galaxia', emoji: '🌌', name: 'Galàxia', series: 'espai', rarity: 'comuna', source: 'joc' },
  { id: 'estel-fugac', emoji: '🌠', name: 'Estel fugaç', series: 'espai', rarity: 'rara', source: 'joc' },
  { id: 'telescopi', emoji: '🔭', name: 'Telescopi', series: 'espai', rarity: 'rara', source: 'joc' },
  { id: 'sol-gran', emoji: '🌞', name: 'Sol somrient', series: 'espai', rarity: 'rara', source: 'joc' },
  { id: 'alienigena', emoji: '👽', name: 'Extraterrestre', series: 'espai', rarity: 'epica', source: 'joc' },
  { id: 'constellacio', emoji: '✨', name: 'Constel·lació', series: 'espai', rarity: 'epica', source: 'joc' },
  { id: 'croissant', emoji: '🥐', name: 'Croissant', series: 'dolcos', rarity: 'comuna', source: 'joc' },
  { id: 'xocolata', emoji: '🍫', name: 'Xocolata', series: 'dolcos', rarity: 'comuna', source: 'joc' },
  { id: 'galeta', emoji: '🍪', name: 'Galeta', series: 'dolcos', rarity: 'comuna', source: 'joc' },
  { id: 'pa-de-pessic', emoji: '🍰', name: 'Pa de pessic', series: 'dolcos', rarity: 'comuna', source: 'joc' },
  { id: 'caramel', emoji: '🍬', name: 'Caramel', series: 'dolcos', rarity: 'comuna', source: 'joc' },
  { id: 'mel', emoji: '🍯', name: 'Pot de mel', series: 'dolcos', rarity: 'comuna', source: 'joc' },
  { id: 'crep', emoji: '🥞', name: 'Creps', series: 'dolcos', rarity: 'comuna', source: 'joc' },
  { id: 'cupcake-rosa', emoji: '🧁💖', name: 'Cupcake rosa', series: 'dolcos', rarity: 'rara', source: 'joc' },
  { id: 'gelat-doble', emoji: '🍨', name: 'Gelat de bola', series: 'dolcos', rarity: 'rara', source: 'joc' },
  { id: 'xurro', emoji: '🥖', name: 'Barra de pa', series: 'dolcos', rarity: 'rara', source: 'joc' },
  { id: 'crema', emoji: '🍮', name: 'Flam', series: 'dolcos', rarity: 'epica', source: 'joc' },
  { id: 'cireres', emoji: '🍒', name: 'Cireres', series: 'dolcos', rarity: 'epica', source: 'joc' },
  { id: 'peix', emoji: '🐟', name: 'Peixet', series: 'mar', rarity: 'comuna', source: 'joc' },
  { id: 'peix-globus', emoji: '🐡', name: 'Peix globus', series: 'mar', rarity: 'comuna', source: 'joc' },
  { id: 'tauro', emoji: '🦈', name: 'Tauró', series: 'mar', rarity: 'comuna', source: 'joc' },
  { id: 'estrella-mar', emoji: '⭐🌊', name: 'Estrella de mar', series: 'mar', rarity: 'comuna', source: 'joc' },
  { id: 'cavallet', emoji: '🦑', name: 'Calamar', series: 'mar', rarity: 'comuna', source: 'joc' },
  { id: 'gamba', emoji: '🦐', name: 'Gamba', series: 'mar', rarity: 'comuna', source: 'joc' },
  { id: 'ancora', emoji: '⚓', name: 'Àncora', series: 'mar', rarity: 'comuna', source: 'joc' },
  { id: 'vaixell', emoji: '⛵', name: 'Veler', series: 'mar', rarity: 'rara', source: 'joc' },
  { id: 'onada', emoji: '🌊', name: 'Onada', series: 'mar', rarity: 'rara', source: 'joc' },
  { id: 'llagosta', emoji: '🦞', name: 'Llagosta', series: 'mar', rarity: 'rara', source: 'joc' },
  { id: 'medusa', emoji: '🪼', name: 'Medusa', series: 'mar', rarity: 'epica', source: 'joc' },
  { id: 'farot', emoji: '🏝️', name: 'Illa petita', series: 'mar', rarity: 'epica', source: 'joc' },
  { id: 'robot-blau', emoji: '🤖', name: 'Robot amic', series: 'robots', rarity: 'comuna', source: 'joc' },
  { id: 'robot-cor', emoji: '🤖💙', name: 'Robot amb cor', series: 'robots', rarity: 'comuna', source: 'joc' },
  { id: 'engranatge', emoji: '⚙️', name: 'Engranatge', series: 'robots', rarity: 'comuna', source: 'joc' },
  { id: 'bateria', emoji: '🔋', name: 'Bateria', series: 'robots', rarity: 'comuna', source: 'joc' },
  { id: 'bombeta', emoji: '💡', name: 'Bombeta', series: 'robots', rarity: 'comuna', source: 'joc' },
  { id: 'clau-anglesa', emoji: '🔧', name: 'Clau anglesa', series: 'robots', rarity: 'comuna', source: 'joc' },
  { id: 'joystick', emoji: '🕹️', name: 'Joystick', series: 'robots', rarity: 'comuna', source: 'joc' },
  { id: 'antena', emoji: '📡', name: 'Antena', series: 'robots', rarity: 'rara', source: 'joc' },
  { id: 'ordinador', emoji: '💻', name: 'Ordinador', series: 'robots', rarity: 'rara', source: 'joc' },
  { id: 'imant', emoji: '🧲', name: 'Imant', series: 'robots', rarity: 'rara', source: 'joc' },
  { id: 'xip', emoji: '🔌', name: 'Endoll', series: 'robots', rarity: 'epica', source: 'joc' },
  { id: 'dron', emoji: '🚁', name: 'Helicòpter', series: 'robots', rarity: 'epica', source: 'joc' },
  { id: 'd-arc', emoji: '🌈', name: 'Arc petit', series: 'repte', rarity: 'rara', source: 'repte' },
  { id: 'd-sol', emoji: '🌤️', name: 'Sol de matí', series: 'repte', rarity: 'rara', source: 'repte' },
  { id: 'd-llamp', emoji: '⚡', name: 'Llampec', series: 'repte', rarity: 'rara', source: 'repte' },
  { id: 'd-cor', emoji: '💗', name: 'Cor valent', series: 'repte', rarity: 'rara', source: 'repte' },
  { id: 'd-trofeu', emoji: '🏆', name: 'Trofeu petit', series: 'repte', rarity: 'rara', source: 'repte' },
  { id: 'd-medalla', emoji: '🏅', name: 'Medalla', series: 'repte', rarity: 'rara', source: 'repte' },
  { id: 'd-cometa', emoji: '🪁', name: 'Estel de paper', series: 'repte', rarity: 'rara', source: 'repte' },
  { id: 'd-diana', emoji: '🎯', name: 'Diana', series: 'repte', rarity: 'rara', source: 'repte' },
  { id: 'd-dau', emoji: '🎲', name: 'Dau de la sort', series: 'repte', rarity: 'epica', source: 'repte' },
  { id: 'd-clau', emoji: '🗝️', name: 'Clau d’or', series: 'repte', rarity: 'epica', source: 'repte' },
  { id: 'd-mapa', emoji: '🗺️', name: 'Mapa del tresor', series: 'repte', rarity: 'epica', source: 'repte' },
  { id: 'd-bruixola', emoji: '🧭', name: 'Brúixola', series: 'repte', rarity: 'epica', source: 'repte' },
  { id: 'serie-bosc', emoji: '🌲', name: 'Mestre del Bosc', series: 'bosc', rarity: 'llegendaria', source: 'serie' },
  { id: 'serie-platja', emoji: '🏖️', name: 'Mestre de la Platja', series: 'platja', rarity: 'llegendaria', source: 'serie' },
  { id: 'serie-castell', emoji: '🏰', name: 'Mestre del Castell', series: 'castell', rarity: 'llegendaria', source: 'serie' },
  { id: 'serie-animals', emoji: '🦁', name: 'Rei dels Animals', series: 'animals', rarity: 'llegendaria', source: 'serie' },
  { id: 'serie-espai', emoji: '🚀', name: 'Explorador de l’Espai', series: 'espai', rarity: 'llegendaria', source: 'serie' },
  { id: 'serie-dolcos', emoji: '🍰', name: 'Llaminer major', series: 'dolcos', rarity: 'llegendaria', source: 'serie' },
  { id: 'serie-mar', emoji: '🐙', name: 'Capità del Mar', series: 'mar', rarity: 'llegendaria', source: 'serie' },
  { id: 'serie-robots', emoji: '🤖', name: 'Inventor de Robots', series: 'robots', rarity: 'llegendaria', source: 'serie' },
  { id: 'serie-repte', emoji: '🏆', name: 'Campió dels Reptes', series: 'repte', rarity: 'llegendaria', source: 'serie' },
]
