/** Kid-facing emoji per game (decorative; always paired with a text title). */
export const GAME_EMOJI: Record<string, string> = {
  'repte-illa': '🏝️',
  'duel-llampec': '⚡',
  'tren-sumes': '🚂',
  'pesca-sumes': '🐟',
  bombolles: '🫧',
  'marc-magic': '🖼️',
  'cursa-recta': '🏁',
  'fleca-files': '🧁',
  llaminadures: '🍬',
  'botiga-pluja': '☂️',
  'numero-amagat': '⚖️',
  'pastis-fraccions': '🍰',
  'laberint-aventura': '🧭',
  'constructor-torres': '🏗️',
  'jardi-arrays': '🌷',
  'domino-sumes': '🁣',
  'piramide-magica': '🔺',
  'cuina-sumes': '🍳',
  'parelles-cartes': '🃏',
  bitlles: '🎳',
  'ritme-taules': '🥁',
  'detectiu-errors': '🕵️',
  'contes-numeros': '📖',
  'escape-room': '🗝️',
}
