/** Kid-facing emoji per game (decorative; always paired with a text title). */
export const GAME_EMOJI: Record<string, string> = {
  'repte-illa': '🏝️',
  'duel-llampec': '⚡',
  'tren-sumes': '🚂',
  'pesca-sumes': '🐟',
  bombolles: '🫧',
  'marc-magic': '🖼️',
  'cursa-recta': '🏁',
  'fleca-files': '🧁',
  llaminadures: '🍬',
  'botiga-pluja': '☂️',
  'numero-amagat': '⚖️',
  'pastis-fraccions': '🍰',
  'laberint-aventura': '🧭',
  'poble-botiga': '🏪',
  'poble-casa': '🏠',
  'poble-autobus': '🚌',
  'poble-perruqueria': '💇',
}
